export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_UPDATED = "USER_UPDATED";

export const VEHICLES_FETCHED = "VEHICLES_FETCHED";
export const VEHICLE_FETCHED = "VEHICLE_FETCHED";
export const VEHICLE_CREATED = "VEHICLE_CREATED";
export const VEHICLE_UPDATED = "VEHICLE_UPDATED";
export const VEHICLE_DELETED = "VEHICLE_DELETED";

export const VEHICLE_SERVICE_RECORDS_FETCHED = "VEHICLE_SERVICE_RECORDS_FETCHED";

export const SERVICE_COMPANIES_FETCHED = "SERVICE_COMPANIES_FETCHED";
export const SERVICE_RECORD_CREATED = "SERVICE_RECORD_CREATED";
export const SERVICE_TYPES_FETCHED = "SERVICE_TYPES_FETCHED";

export const VEHICLE_SERVICE_RECORD_FETCHED = "VEHICLE_SERVICE_RECORD_FETCHED";
export const VEHICLE_SERVICE_RECORD_UPDATED = "VEHICLE_SERVICE_RECORD_UPDATED";

