export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const USER_UPDATED = "USER_UPDATED";

export const VEHICLES_FETCHED = "VEHICLES_FETCHED";
export const VEHICLE_FETCHED = "VEHICLE_FETCHED";
export const VEHICLE_CREATED = "VEHICLE_CREATED";
export const VEHICLE_UPDATED = "VEHICLE_UPDATED";
export const VEHICLE_DELETED = "VEHICLE_DELETED";

